src/java/faculdade/controller/DisciplinaController.java
package faculdade.controller;

import faculdade.dao.Disciplina;
import faculdade.controller.util.JsfUtil;
import faculdade.controller.util.JsfUtil.PersistAction;
import faculdade.service.DisciplinaFacade;
import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("disciplinaController")
@SessionScoped
public class DisciplinaController implements Serializable {

    @EJB
    private faculdade.service.DisciplinaFacade ejbFacade;
    private List<Disciplina> items = null;
    private Disciplina selected;

    public DisciplinaController() {
    }

    public Disciplina getSelected() {
        return selected;
    }

    public void setSelected(Disciplina selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
        selected.getDisciplinaPK().setCursoid(selected.getCurso().getId());
    }

    protected void initializeEmbeddableKey() {
        selected.setDisciplinaPK(new faculdade.dao.DisciplinaPK());
    }

    private DisciplinaFacade getFacade() {
        return ejbFacade;
    }

    public Disciplina prepareCreate() {
        selected = new Disciplina();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("DisciplinaCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("DisciplinaUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("DisciplinaDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Disciplina> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    /**
     * Executa quaisquer ações de modificação de dados para uma entidade. As
     * ações que Podem ser realizados por este método são controlados pelo
     * Enumeração {@link PersistAction} e são CREATE, EDIT ou DELETE.
     *
     * @param persistAction uma ação específica que deve ser executada no Item
     * atual
     * @param successMessage uma mensagem que deve ser exibida quando
     * persistindo O item é bem-sucedido
     */
    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Disciplina getDisciplina(faculdade.dao.DisciplinaPK id) {
        return getFacade().find(id);
    }

    public List<Disciplina> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Disciplina> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Disciplina.class)
    public static class DisciplinaControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DisciplinaController controller = (DisciplinaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "disciplinaController");
            return controller.getDisciplina(getKey(value));
        }

        faculdade.dao.DisciplinaPK getKey(String value) {
            faculdade.dao.DisciplinaPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new faculdade.dao.DisciplinaPK();
            key.setId(Integer.parseInt(values[0]));
            key.setCursoid(Integer.parseInt(values[1]));
            return key;
        }

        String getStringKey(faculdade.dao.DisciplinaPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getId());
            sb.append(SEPARATOR);
            sb.append(value.getCursoid());
            return sb.toString();
        }

        /**
         *
         * @param facesContext
         * @param component
         * @param object
         * @return é um metodo que retorna um objeto verdadeiro
         */
        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Disciplina) {
                Disciplina o = (Disciplina) object;
                return getStringKey(o.getDisciplinaPK());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Disciplina.class.getName()});
                return null;
            }
        }

    }

}

web/disciplina/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="DisciplinaCreateDlg" widgetVar="DisciplinaCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateDisciplinaTitle}">
            <h:form id="DisciplinaCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{disciplinaController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateDisciplinaLabel_nome}" for="nome" />
                        <p:inputText id="nome" value="#{disciplinaController.selected.nome}" title="#{bundle.CreateDisciplinaTitle_nome}" />
                        <p:outputLabel value="#{bundle.CreateDisciplinaLabel_cargahoraria}" for="cargahoraria" />
                        <p:calendar id="cargahoraria" pattern="HH:mm:ss" value="#{disciplinaController.selected.cargahoraria}" title="#{bundle.EditDisciplinaTitle_cargahoraria}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateDisciplinaLabel_curso}" for="curso" />
                        <p:selectOneMenu id="curso" value="#{disciplinaController.selected.curso}" required="true" requiredMessage="#{bundle.EditDisciplinaRequiredMessage_curso}">
                            <f:selectItems value="#{cursoController.itemsAvailableSelectOne}"
                                           var="cursoItem"
                                           itemValue="#{cursoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{disciplinaController.create}" value="#{bundle.Save}" update="display,:DisciplinaListForm:datalist,:growl" oncomplete="handleSubmit(args,'DisciplinaCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="DisciplinaCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/disciplina/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="DisciplinaEditDlg" widgetVar="DisciplinaEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditDisciplinaTitle}">
            <h:form id="DisciplinaEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{disciplinaController.selected != null}">
                        <p:outputLabel value="#{bundle.EditDisciplinaLabel_nome}" for="nome" />
                        <p:inputText id="nome" value="#{disciplinaController.selected.nome}" title="#{bundle.EditDisciplinaTitle_nome}" />
                        <p:outputLabel value="#{bundle.EditDisciplinaLabel_cargahoraria}" for="cargahoraria" />
                        <p:calendar id="cargahoraria" pattern="HH:mm:ss" value="#{disciplinaController.selected.cargahoraria}" title="#{bundle.EditDisciplinaTitle_cargahoraria}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditDisciplinaLabel_curso}" for="curso" />
                        <p:selectOneMenu id="curso" value="#{disciplinaController.selected.curso}" required="true" requiredMessage="#{bundle.EditDisciplinaRequiredMessage_curso}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{cursoController.itemsAvailableSelectOne}"
                                           var="cursoItem"
                                           itemValue="#{cursoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{disciplinaController.update}" value="#{bundle.Save}" update="display,:DisciplinaListForm:datalist,:growl" oncomplete="handleSubmit(args, 'DisciplinaEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="DisciplinaEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/disciplina/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListDisciplinaTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="DisciplinaListForm">
                <p:panel header="#{bundle.ListDisciplinaTitle}">
                    <p:dataTable id="datalist" value="#{disciplinaController.items}" var="item"
                                 selectionMode="single" selection="#{disciplinaController.selected}"
                                 paginator="true"
                                 rowKey="#{item.disciplinaPK}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDisciplinaTitle_disciplinaPK_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.disciplinaPK.id}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDisciplinaTitle_nome}"/>
                            </f:facet>
                            <h:outputText value="#{item.nome}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDisciplinaTitle_cargahoraria}"/>
                            </f:facet>
                            <h:outputText value="#{item.cargahoraria}">
                                <f:convertDateTime pattern="HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDisciplinaTitle_curso}"/>
                            </f:facet>
                            <h:outputText value="#{item.curso.nome}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{disciplinaController.prepareCreate}" update=":DisciplinaCreateForm" oncomplete="PF('DisciplinaCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":DisciplinaViewForm" oncomplete="PF('DisciplinaViewDialog').show()" disabled="#{empty disciplinaController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":DisciplinaEditForm" oncomplete="PF('DisciplinaEditDialog').show()" disabled="#{empty disciplinaController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{disciplinaController.destroy}" update=":growl,datalist" disabled="#{empty disciplinaController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/disciplina/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="DisciplinaViewDlg" widgetVar="DisciplinaViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewDisciplinaTitle}">
            <h:form id="DisciplinaViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{disciplinaController.selected != null}">
                        <h:outputText value="#{bundle.ViewDisciplinaLabel_disciplinaPK_id}"/>
                        <h:outputText value="#{disciplinaController.selected.disciplinaPK.id}" title="#{bundle.ViewDisciplinaTitle_disciplinaPK_id}"/>
                        <h:outputText value="#{bundle.ViewDisciplinaLabel_nome}"/>
                        <h:outputText value="#{disciplinaController.selected.nome}" title="#{bundle.ViewDisciplinaTitle_nome}"/>
                        <h:outputText value="#{bundle.ViewDisciplinaLabel_cargahoraria}"/>
                        <h:outputText value="#{disciplinaController.selected.cargahoraria}" title="#{bundle.ViewDisciplinaTitle_cargahoraria}">
                            <f:convertDateTime pattern="HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewDisciplinaLabel_curso}"/>
                        <h:outputText value="#{disciplinaController.selected.curso}" title="#{bundle.ViewDisciplinaTitle_curso}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="DisciplinaViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>